### ISSUE TITLE
Undefined function mb_regex when applying featured image

### ISSUE THREAD

**Issue by ilyashrn** [themejack/briar#3]
When featured image is applied, it happens. Please help. 

![screen shot 2016-11-24 at 2 15 20 pm](https://cloud.githubusercontent.com/assets/13843296/20589665/810d3664-b250-11e6-8904-8722b631c879.png)

**Comment by progcode** [comment]
In the template-tags.php line 329 comment off the following functions: `$content = trim( mb_ereg_replace( '\s+', ' ', $content ) );`

**Comment by anteprimorac** [comment]
Fixed in v1.1.10
