### ISSUE TITLE
Languages path and default .po file not exists

### ISSUE THREAD

**Issue by progcode** [themejack/briar#4]
Languages path and default .po file not exists
`load_theme_textdomain( 'briar', get_template_directory() . '/languages' );`

**Comment by anteprimorac** [comment]
Hi @progcode,
thanks for noticing this. I will generate .pot file and put it into languages folder, but you don't need to wait for it you can translate theme trough GlotPress - [https://translate.wordpress.org/projects/wp-themes/briar](https://translate.wordpress.org/projects/wp-themes/briar).

**Comment by anteprimorac** [comment]
Fixed in v1.1.10
